INSERT INTO ADDRESS(ID, STREET, CITY, STATE, ZIPCODE)
VALUES (1, '485 Lindbergh Pl NE', 'Atlanta', 'GA', 30324);

INSERT INTO APARTMENT(COMPANY, NAME, SQ_FT, PRICE, ADDRESS_ID)
VALUES('The Pointe At Lindbergh', 'A6', 1042, 1652, 1);
INSERT INTO APARTMENT(COMPANY, NAME, SQ_FT, PRICE, ADDRESS_ID)
VALUES('The Pointe At Lindbergh', 'B', 946, 1768, 1);
INSERT INTO APARTMENT(COMPANY, NAME, SQ_FT, PRICE, ADDRESS_ID)
VALUES('The Pointe At Lindbergh', 'C', 1029, 1933, 1);
INSERT INTO APARTMENT(COMPANY, NAME, SQ_FT, PRICE, ADDRESS_ID)
VALUES('The Pointe At Lindbergh', 'C1', 1042, 1867, 1);
INSERT INTO APARTMENT(COMPANY, NAME, SQ_FT, PRICE, ADDRESS_ID)
VALUES('The Pointe At Lindbergh', 'C2', 1150, 1668, 1);