INSERT INTO ADDRESS(ID, STREET, CITY, STATE, ZIPCODE)
VALUES (1, '1000 Lexington Farms Drive', 'Alpharetta', 'GA', 30009);

INSERT INTO APARTMENT(COMPANY, NAME, SQFT, PRICE, ADDRESS_ID)
VALUES('The Lex', 'Belgian', 993, 1393, 1);
INSERT INTO APARTMENT(COMPANY, NAME, SQFT, PRICE, ADDRESS_ID)
VALUES('The Lex', 'Morgan', 1091, 1491, 1);