INSERT INTO ADDRESS(ID, STREET, CITY, STATE, ZIPCODE)
VALUES (1, '485 Lindbergh Pl NE', 'Atlanta', 'GA', 30324);
INSERT INTO ADDRESS(ID, STREET, CITY, STATE, ZIPCODE)
VALUES(2, '2450 Camellia Ln NE', 'Atlanta', 'GA', 30324);

INSERT INTO APARTMENT(COMPANY, NAME, SQ_FT, PRICE, ADDRESS_ID)
VALUES('The Pointe At Lindbergh', 'A6', 1042, 1652, 1);
INSERT INTO APARTMENT(COMPANY, NAME, SQ_FT, PRICE, ADDRESS_ID)
VALUES('The Pointe At Lindbergh', 'B', 946, 1768, 1);
INSERT INTO APARTMENT(COMPANY, NAME, SQ_FT, PRICE, ADDRESS_ID)
VALUES('The Pointe At Lindbergh', 'C', 1029, 1933, 1);
INSERT INTO APARTMENT(COMPANY, NAME, SQ_FT, PRICE, ADDRESS_ID)
VALUES('The Pointe At Lindbergh', 'C1', 1042, 1867, 1);
INSERT INTO APARTMENT(COMPANY, NAME, SQ_FT, PRICE, ADDRESS_ID)
VALUES('The Pointe At Lindbergh', 'C2', 1150, 1668, 1);
INSERT INTO APARTMENT(COMPANY, NAME, SQ_FT, PRICE, ADDRESS_ID)
VALUES('eon at Lindberg', 'A12', 872, 1480, 2);
INSERT INTO APARTMENT(COMPANY, NAME, SQ_FT, PRICE, ADDRESS_ID)
VALUES('eon at Lindberg', 'D4', 1054, 1591, 2);
INSERT INTO APARTMENT(COMPANY, NAME, SQ_FT, PRICE, ADDRESS_ID)
VALUES('eon at Lindberg', 'D5', 1054, 1641, 2);
INSERT INTO APARTMENT(COMPANY, NAME, SQ_FT, PRICE, ADDRESS_ID)
VALUES('eon at Lindberg', 'D6L', 1065, 1611, 2);
INSERT INTO APARTMENT(COMPANY, NAME, SQ_FT, PRICE, ADDRESS_ID)
VALUES('eon at Lindberg', 'D7L', 1080, 1608, 2);
INSERT INTO APARTMENT(COMPANY, NAME, SQ_FT, PRICE, ADDRESS_ID)
VALUES('eon at Lindberg', 'D8', 1086, 1683, 2);
